from enum import Enum


TRANSMISSION_STATUS_FRAME = 0x0
TRANSPORT_LAYER_FRAME = 0x1
BOOTLOADER_FRAME = 0x2
UNKNOWN_FRAME = 0xFF

ACK = 0x0
TRANSMISSION_ERROR = 0x1

FLOW_CONTROL = 0x0

#FLOW CONTROL TYPES
CTS = 0x0
WAIT = 0x1
ERROR = 0x2
FINISH = 0x3

#BTLD COMMANDS
BTLD_ACTIVATE = 0x0 	# + ID
BTLD_PROGRAM_SIZE = 0x1 		# + PROGRAM SIZE
BTLD_ACK = 0x2
BTLD_ERROR = 0x3 			# + ERROR ID
BTLD_CRC = 0x4				# + CRC of memory
BTLD_FINISH = 0x5
BTLD_ABORT = 0x6


TOO_LONG = 0x0
TOO_SHORT = 0x1
BAD_CRC = 0x2
NO_START_BYTE = 0x3